spring:
  application:
    name: springboot-keycloak
  security:
    oauth2:
      client:
        registration:
            keycloak:
                client-id: vis-backend
                authorization-grant-type: authorization_code
                scope: openid
                client-secret: yUZug8Bd8gKsibuZdriEcKajXGDrzJWd
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/7vis
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/7vis
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: vis-backend
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '8081'
  servlet:
    context-path: /v1/api
